apiVersion: v1
kind: Service
metadata:
  name: my-hello-world
  labels:
    app: helloworld
spec:
  type: app
  ports:
  - port: 80
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hello-world
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: my-hello-world
        image: node:16
        ports:
        - containerPort: 80
